# Change these first
owner: laurentS # Your GitHub organization or username, where this repository lives
repo: myupptime # The name of this repository

sites:
  ###### MaDada ######
  - name: MaDada frontpage
    url: https://madada.fr
  - name: MaDada blog
    url: https://blog.madada.fr
  - name: MaDada authorities list
    url: https://madada.fr/body/list/all
  - name: MaDada user page
    url: https://madada.fr/user/laurent_savaete
  ###### MapSwipe ######
  - name: MapSwipe public page
    url: https://mapswipe.org
  ###### OpenFinData ######
  - name: OpenFinData landing page
    url: https://openfindata.io
  - name: OpenFinData API docs
    url: https://api.openfindata.io/docs
  - name: OpenFinData public summary example
    url: https://api.openfindata.io/api/v1/funds/summary_public/US47103E1221


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /myupptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Some Upptime stats :)
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Status page with **real-time** data.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
